### ISSUE TITLE
Vanilla create-zudoku-app throws warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by zamd** [zuplo/zudoku#192]
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at io (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/zudoku.components.js:2321:21)
    at Jt (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/zudoku.components.js:2843:26)
    at xl (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/zudoku.components.js:2903:32)
    at div
    at div
    at div
    at header
    at file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/zudoku.components.js:2982:13
    at Ol (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/zudoku.components.js:3331:22)
    at Pb (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/Markdown-BZUoEvL7.js:2548:13)
    at Le (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/SlotletProvider-CNyl5wU0.js:250:13)
    at El (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/zudoku.components.js:3045:18)
    at We (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/utils-BPHLKjns.js:22:12)
    at Cl (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/zudoku.components.js:3056:13)
    at He (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/ZudokuContext-BHNQL3XO.js:921:11)
    at Rl (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/zudoku.components.js:3062:13)
    at Ss (file:///Users/zahmed/authlete/spikes/authlete-docs/node_modules/zudoku/lib/zudoku.components.js:845:5)
    at DevPortal
    ```

**Comment by dan-lee** [comment]
Hm I think this should've been fixed already. It looks like, for some reason, `create-zudoku-app` installs an outdated version of `zudoku`. Can you try upgrading to v0.6.1 in `package.json` manually?

**Comment by dan-lee** [comment]
This should be fixed. Let me know if you still see this
