### ISSUE TITLE
TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file

### ISSUE THREAD

**Issue by majoshi1** [zuplo/zudoku#226]
Getting error while starting a freshly created app. Any idea?
OS: Windows 10.
Client: Cmd

```
> npm create zudoku-app@latest

> npx
> create-zudoku-app

√ What is your project named? ... zudoku-app
√ Would you like to use TypeScript? ... No
√ Would you like to use ESLint? ... Yes
Creating a new Zudoku app in c:\opt\zudoku-app.

Using npm.

Initializing project with template: default


Installing dependencies:
- react
- react-dom
- zudoku

Installing devDependencies:
- eslint
. . .

> cd zudoku-app
> npm run dev

> zudoku-app1@0.1.0 dev
> zudoku dev

7:37:22 PM zudoku loaded config file C:\opt\zudoku-app1\zudoku.config.mjs
node:internal/event_target:1094
  process.nextTick(() => { throw err; });
                           ^

TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at fileURLToPath (node:internal/url:1463:11)
    at onImport (file:///C:/opt/zudoku-app1/node_modules/.pnpm/zudoku@0.10.0_@internationalized+date@3.5.5_@types+node@22.5.5_@types+react@18.3.8_@urql+core_qbngxlopj3evntnosxwxt4mpou/node_modules/zudoku/dist/vite/config.js:55:30)
    at MessagePort.n (file:///C:/opt/zudoku-app1/node_modules/.pnpm/tsx@4.19.0/node_modules/tsx/dist/register-BArwRho-.mjs:1:1098)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_URL_SCHEME'
}

Node.js v20.17.0
```

**Comment by ekimcoskun** [comment]
same issue

**Comment by wesleylimacosta** [comment]
rt

**Comment by dan-lee** [comment]
This should be fixed in https://github.com/zuplo/zudoku/releases/tag/v0.12.0
