### ISSUE TITLE
File not found for document 'introduction'. Check your sidebar configuration.

### ISSUE THREAD

**Issue by majoshi1** [zuplo/zudoku#256]
Getting error while starting a freshly created app. Any idea?
OS: Windows 10.
Client: Git Bash

```
$ npm create zudoku-app@latest
npm warn exec The following package was not found and will be installed: create-zudoku-app@0.12.0

> npx
> create-zudoku-app

√ What is your project named? ... zudoku-app3
√ Would you like to use TypeScript? ... No
√ Would you like to use ESLint? ... Yes
Creating a new Zudoku app in C:\opt\zudoku-app3.

Using npm.

Initializing project with template: default


Installing dependencies:
- react
- react-dom
- zudoku

Installing devDependencies:
- eslint

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.

added 1208 packages, and audited 1210 packages in 3m

288 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (1 low, 3 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
Initialized a git repository.

Success! Created zudoku-app3 at C:\opt\zudoku-app3


$ cd zudoku-app3

$ npm run dev

> zudoku-app3@0.1.0 dev
> zudoku dev

5:12:19 AM zudoku loaded config file C:\opt\zudoku-app3\zudoku.config.mjs
Server-side rendering enabled
Started development server
Ctrl+C to exit

🚀 Zudoku Portal: http://localhost:9000

5:12:59 AM zudoku Pre-transform error: File not found for document 'introduction'. Check your sidebar configuration.
5:13:02 AM zudoku Error when evaluating SSR module /node_modules/zudoku/src/app/main.tsx:
|- Error: File not found for document 'introduction'. Check your sidebar configuration.
    at resolveDoc (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/config/validators/SidebarSchema.js:11:19)
    at async Promise.all (index 0)
    at async resolveSidebarItem (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/config/validators/SidebarSchema.js:68:31)
    at async Promise.all (index 0)
    at async file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/vite/plugin-sidebar.js:32:17
    at async Promise.all (index 0)
    at async LoadPluginContext.load (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/vite/plugin-sidebar.js:30:56)
    at async PluginContainer.load (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:48753:22)
    at async loadAndTransform (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:51548:22)
    at async instantiateModule (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52551:44)

5:13:02 AM zudoku Error when evaluating SSR module C:/opt/zudoku-app3/node_modules/zudoku/src/app/entry.server.tsx:
|- Error: File not found for document 'introduction'. Check your sidebar configuration.
    at resolveDoc (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/config/validators/SidebarSchema.js:11:19)
    at async Promise.all (index 0)
    at async resolveSidebarItem (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/config/validators/SidebarSchema.js:68:31)
    at async Promise.all (index 0)
    at async file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/vite/plugin-sidebar.js:32:17
    at async Promise.all (index 0)
    at async LoadPluginContext.load (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/vite/plugin-sidebar.js:30:56)
    at async PluginContainer.load (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:48753:22)
    at async loadAndTransform (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:51548:22)
    at async instantiateModule (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52551:44)

Error: File not found for document 'introduction'. Check your sidebar configuration.
    at resolveDoc (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/config/validators/SidebarSchema.js:11:19)
    at async Promise.all (index 0)
    at async resolveSidebarItem (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/config/validators/SidebarSchema.js:68:31)
    at async Promise.all (index 0)
    at async file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/vite/plugin-sidebar.js:32:17
    at async Promise.all (index 0)
    at async LoadPluginContext.load (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/vite/plugin-sidebar.js:30:56)
    at async PluginContainer.load (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:48753:22)
    at async loadAndTransform (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:51548:22)
    at async instantiateModule (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52551:44)
Error: File not found for document 'introduction'. Check your sidebar configuration.
    at resolveDoc (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/config/validators/SidebarSchema.js:11:19)
    at async Promise.all (index 0)
    at async resolveSidebarItem (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/config/validators/SidebarSchema.js:68:31)
    at async Promise.all (index 0)
    at async file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/vite/plugin-sidebar.js:32:17
    at async Promise.all (index 0)
    at async LoadPluginContext.load (file:///C:/opt/zudoku-app3/node_modules/zudoku/dist/vite/plugin-sidebar.js:30:56)
    at async PluginContainer.load (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:48753:22)
    at async loadAndTransform (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:51548:22)
    at async instantiateModule (file:///C:/opt/zudoku-app3/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52551:44)



Node.js v20.17.0
```

**Comment by dan-lee** [comment]
Oh, looks like the default template for the JS version is out of date. It should work fine, but the config has not been updated.

Sorry, I'll fix that

**Comment by majoshi1** [comment]
Thanks, that helped! Is it possible to avoid call to github.com, while running the application? Related issue: https://github.com/zuplo/zudoku/issues/228
