### ISSUE TITLE
Cannot find module 'zudoku/plugins/openapi' imported from 'virtual:zudoku-api-plugins'

### ISSUE THREAD

**Issue by majoshi1** [zuplo/zudoku#257]
Getting error while starting from cloned repo. Any idea?
OS: Windows 10.
Client: Git Bash

```
$ git clone https://github.com/zuplo/zudoku.git
Cloning into 'zudoku'...
remote: Enumerating objects: 3916, done.
remote: Counting objects: 100% (1483/1483), done.
remote: Compressing objects: 100% (510/510), done.
remote: Total 3916 (delta 1173), reused 1183 (delta 961), pack-reused 2433 (from 1)
Receiving objects: 100% (3916/3916), 1.96 MiB | 2.97 MiB/s, done.
Resolving deltas: 100% (2296/2296), done.

$ cd zudoku

$ pnpm i

. . .
Done in 2m 58.5s

$ nx run with-config:dev --verbose

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  The "nx/js/dependencies-and-lockfile" plugin threw an error while creating dependencies:
    Error: Source project does not exist: npm:@0no-co/graphql.web@1.0.8
        at validateCommonDependencyRules (C:\opt\zudoku\node_modules\nx\src\project-graph\project-graph-builder.js:318:15)
        at validateDependency (C:\opt\zudoku\node_modules\nx\src\project-graph\project-graph-builder.js:314:5)
        at C:\opt\zudoku\node_modules\nx\src\plugins\js\lock-file\pnpm-parser.js:265:76
        at Array.forEach (<anonymous>)
        at C:\opt\zudoku\node_modules\nx\src\plugins\js\lock-file\pnpm-parser.js:255:45
        at Array.forEach (<anonymous>)
        at C:\opt\zudoku\node_modules\nx\src\plugins\js\lock-file\pnpm-parser.js:253:68
        at Set.forEach (<anonymous>)
        at C:\opt\zudoku\node_modules\nx\src\plugins\js\lock-file\pnpm-parser.js:252:15
        at Array.forEach (<anonymous>)


$ nx reset

 NX   Resetting the Nx cache and stopping the daemon.



 NX   Successfully reset the Nx workspace.


$ nx run with-config:dev --verbose

 NX   Running target dev for project with-config and 1 task it depends on:



> nx run zudoku:build


> zudoku@0.12.0 build C:\opt\zudoku\packages\zudoku
> tsc --project tsconfig.json


> nx run with-config:dev

> with-config@0.0.1 dev C:\opt\zudoku\examples\with-config
> zudoku dev
5:44:09 AM zudoku loaded config file C:\opt\zudoku\examples\with-config\zudoku.config.ts
Server-side rendering enabled
Started development server
Ctrl+C to exit

🚀 Zudoku Portal: http://localhost:9000

Error: The following dependencies are imported but could not be resolved:
  zudoku/plugins/custom-page (imported by C:/opt/zudoku/packages/zudoku/src/app/main.tsx)
  zudoku/plugins/search-inkeep (imported by C:/opt/zudoku/packages/zudoku/src/app/main.tsx)
Are they installed?
    at file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:50346:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:49851:26
5:44:47 AM zudoku Pre-transform error: Failed to load url zudoku/plugins/custom-page (resolved id: zudoku/plugins/custom-page) in C:/opt/zudoku/packages/zudoku/src/app/main.tsx. Does the file exist?
5:44:47 AM zudoku Pre-transform error: Failed to load url zudoku/plugins/search-inkeep (resolved id: zudoku/plugins/search-inkeep) in C:/opt/zudoku/packages/zudoku/src/app/main.tsx. Does the file exist?
5:44:47 AM zudoku Pre-transform error: Failed to load url zudoku/plugins/openapi (resolved id: zudoku/plugins/openapi) in virtual:zudoku-api-plugins. Does the file exist?
5:44:47 AM zudoku Pre-transform error: Failed to load url zudoku/plugins/redirect (resolved id: zudoku/plugins/redirect) in virtual:zudoku-redirect-plugin. Does the file exist?
5:44:50 AM zudoku Pre-transform error: Failed to load url zudoku/plugins/markdown (resolved id: zudoku/plugins/markdown) in virtual:zudoku-docs-plugins. Does the file exist?
5:45:02 AM zudoku Error when evaluating SSR module virtual:zudoku-api-plugins: failed to import "zudoku/plugins/openapi"
|- Error: Cannot find module 'zudoku/plugins/openapi' imported from 'virtual:zudoku-api-plugins'
    at nodeImport (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52726:19)
    at ssrImport (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52591:22)
    at eval (virtual:zudoku-api-plugins:3:50)
    at instantiateModule (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52650:11)

5:45:02 AM zudoku Error when evaluating SSR module /@fs/C:/opt/zudoku/packages/zudoku/src/app/main.tsx: failed to import "zudoku/plugins/openapi"
|- Error: Cannot find module 'zudoku/plugins/openapi' imported from 'virtual:zudoku-api-plugins'
    at nodeImport (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52726:19)
    at ssrImport (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52591:22)
    at eval (virtual:zudoku-api-plugins:3:50)
    at instantiateModule (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52650:11)

5:45:02 AM zudoku Error when evaluating SSR module C:/opt/zudoku/packages/zudoku/src/app/entry.server.tsx: failed to import "zudoku/plugins/openapi"
|- Error: Cannot find module 'zudoku/plugins/openapi' imported from 'virtual:zudoku-api-plugins'
    at nodeImport (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52726:19)
    at ssrImport (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52591:22)
    at eval (virtual:zudoku-api-plugins:3:50)
    at instantiateModule (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52650:11)

Error: Cannot find module 'zudoku/plugins/openapi' imported from 'virtual:zudoku-api-plugins'
    at nodeImport (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52726:19)
    at ssrImport (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52591:22)
    at eval (virtual:zudoku-api-plugins:3:50)
    at instantiateModule (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52650:11) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Error: Cannot find module 'zudoku/plugins/openapi' imported from 'virtual:zudoku-api-plugins'
    at nodeImport (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52726:19)
    at ssrImport (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52591:22)
    at eval (virtual:zudoku-api-plugins:3:50)
    at instantiateModule (file:///C:/opt/zudoku/node_modules/.pnpm/vite@5.3.6_@types+node@20.12.10/node_modules/vite/dist/node/chunks/dep-D1AKSjGu.js:52650:11) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by dan-lee** [comment]
Oh yeah, if you work on the mono repo directly, you need to set `ZUDOKU_INTERNAL_DEV=1` as environment variable.

On Windows powershell I think it's `$env:ZUDOKU_INTERNAL_DEV=1`

If you have something like `direnv`, you can copy `.env.example` to `.env` in the root folder.
I guess this missing in the docs, we need to add it

**Comment by majoshi1** [comment]
Thanks, that worked!
